# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amajm/CS100Labs/redone/lab-09-iterator-pattern-lab-9-abdullah-and-richard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amajm/CS100Labs/redone/lab-09-iterator-pattern-lab-9-abdullah-and-richard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amajm/CS100Labs/redone/lab-09-iterator-pattern-lab-9-abdullah-and-richard/CMakeFiles /home/amajm/CS100Labs/redone/lab-09-iterator-pattern-lab-9-abdullah-and-richard/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amajm/CS100Labs/redone/lab-09-iterator-pattern-lab-9-abdullah-and-richard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named lab

# Build rule for target.
lab: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lab
.PHONY : lab

# fast build rule for target.
lab/fast:
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/build
.PHONY : lab/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

AbstractFactorySubs/Precision.o: AbstractFactorySubs/Precision.cpp.o

.PHONY : AbstractFactorySubs/Precision.o

# target to build an object file
AbstractFactorySubs/Precision.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/Precision.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/Precision.cpp.o
.PHONY : AbstractFactorySubs/Precision.cpp.o

AbstractFactorySubs/Precision.i: AbstractFactorySubs/Precision.cpp.i

.PHONY : AbstractFactorySubs/Precision.i

# target to preprocess a source file
AbstractFactorySubs/Precision.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/Precision.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/Precision.cpp.i
.PHONY : AbstractFactorySubs/Precision.cpp.i

AbstractFactorySubs/Precision.s: AbstractFactorySubs/Precision.cpp.s

.PHONY : AbstractFactorySubs/Precision.s

# target to generate assembly for a file
AbstractFactorySubs/Precision.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/Precision.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/Precision.cpp.s
.PHONY : AbstractFactorySubs/Precision.cpp.s

AbstractFactorySubs/Sci.o: AbstractFactorySubs/Sci.cpp.o

.PHONY : AbstractFactorySubs/Sci.o

# target to build an object file
AbstractFactorySubs/Sci.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/Sci.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/Sci.cpp.o
.PHONY : AbstractFactorySubs/Sci.cpp.o

AbstractFactorySubs/Sci.i: AbstractFactorySubs/Sci.cpp.i

.PHONY : AbstractFactorySubs/Sci.i

# target to preprocess a source file
AbstractFactorySubs/Sci.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/Sci.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/Sci.cpp.i
.PHONY : AbstractFactorySubs/Sci.cpp.i

AbstractFactorySubs/Sci.s: AbstractFactorySubs/Sci.cpp.s

.PHONY : AbstractFactorySubs/Sci.s

# target to generate assembly for a file
AbstractFactorySubs/Sci.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/Sci.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/Sci.cpp.s
.PHONY : AbstractFactorySubs/Sci.cpp.s

AbstractFactorySubs/StdDouble.o: AbstractFactorySubs/StdDouble.cpp.o

.PHONY : AbstractFactorySubs/StdDouble.o

# target to build an object file
AbstractFactorySubs/StdDouble.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/StdDouble.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/StdDouble.cpp.o
.PHONY : AbstractFactorySubs/StdDouble.cpp.o

AbstractFactorySubs/StdDouble.i: AbstractFactorySubs/StdDouble.cpp.i

.PHONY : AbstractFactorySubs/StdDouble.i

# target to preprocess a source file
AbstractFactorySubs/StdDouble.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/StdDouble.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/StdDouble.cpp.i
.PHONY : AbstractFactorySubs/StdDouble.cpp.i

AbstractFactorySubs/StdDouble.s: AbstractFactorySubs/StdDouble.cpp.s

.PHONY : AbstractFactorySubs/StdDouble.s

# target to generate assembly for a file
AbstractFactorySubs/StdDouble.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/AbstractFactorySubs/StdDouble.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/AbstractFactorySubs/StdDouble.cpp.s
.PHONY : AbstractFactorySubs/StdDouble.cpp.s

Containers/ListContainer.o: Containers/ListContainer.cpp.o

.PHONY : Containers/ListContainer.o

# target to build an object file
Containers/ListContainer.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Containers/ListContainer.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Containers/ListContainer.cpp.o
.PHONY : Containers/ListContainer.cpp.o

Containers/ListContainer.i: Containers/ListContainer.cpp.i

.PHONY : Containers/ListContainer.i

# target to preprocess a source file
Containers/ListContainer.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Containers/ListContainer.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Containers/ListContainer.cpp.i
.PHONY : Containers/ListContainer.cpp.i

Containers/ListContainer.s: Containers/ListContainer.cpp.s

.PHONY : Containers/ListContainer.s

# target to generate assembly for a file
Containers/ListContainer.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Containers/ListContainer.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Containers/ListContainer.cpp.s
.PHONY : Containers/ListContainer.cpp.s

Containers/VectorCont.o: Containers/VectorCont.cpp.o

.PHONY : Containers/VectorCont.o

# target to build an object file
Containers/VectorCont.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Containers/VectorCont.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Containers/VectorCont.cpp.o
.PHONY : Containers/VectorCont.cpp.o

Containers/VectorCont.i: Containers/VectorCont.cpp.i

.PHONY : Containers/VectorCont.i

# target to preprocess a source file
Containers/VectorCont.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Containers/VectorCont.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Containers/VectorCont.cpp.i
.PHONY : Containers/VectorCont.cpp.i

Containers/VectorCont.s: Containers/VectorCont.cpp.s

.PHONY : Containers/VectorCont.s

# target to generate assembly for a file
Containers/VectorCont.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Containers/VectorCont.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Containers/VectorCont.cpp.s
.PHONY : Containers/VectorCont.cpp.s

Iterator/BinaryIterator.o: Iterator/BinaryIterator.cpp.o

.PHONY : Iterator/BinaryIterator.o

# target to build an object file
Iterator/BinaryIterator.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/BinaryIterator.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/BinaryIterator.cpp.o
.PHONY : Iterator/BinaryIterator.cpp.o

Iterator/BinaryIterator.i: Iterator/BinaryIterator.cpp.i

.PHONY : Iterator/BinaryIterator.i

# target to preprocess a source file
Iterator/BinaryIterator.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/BinaryIterator.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/BinaryIterator.cpp.i
.PHONY : Iterator/BinaryIterator.cpp.i

Iterator/BinaryIterator.s: Iterator/BinaryIterator.cpp.s

.PHONY : Iterator/BinaryIterator.s

# target to generate assembly for a file
Iterator/BinaryIterator.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/BinaryIterator.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/BinaryIterator.cpp.s
.PHONY : Iterator/BinaryIterator.cpp.s

Iterator/NullIterator.o: Iterator/NullIterator.cpp.o

.PHONY : Iterator/NullIterator.o

# target to build an object file
Iterator/NullIterator.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/NullIterator.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/NullIterator.cpp.o
.PHONY : Iterator/NullIterator.cpp.o

Iterator/NullIterator.i: Iterator/NullIterator.cpp.i

.PHONY : Iterator/NullIterator.i

# target to preprocess a source file
Iterator/NullIterator.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/NullIterator.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/NullIterator.cpp.i
.PHONY : Iterator/NullIterator.cpp.i

Iterator/NullIterator.s: Iterator/NullIterator.cpp.s

.PHONY : Iterator/NullIterator.s

# target to generate assembly for a file
Iterator/NullIterator.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/NullIterator.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/NullIterator.cpp.s
.PHONY : Iterator/NullIterator.cpp.s

Iterator/PreOrderIterator.o: Iterator/PreOrderIterator.cpp.o

.PHONY : Iterator/PreOrderIterator.o

# target to build an object file
Iterator/PreOrderIterator.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/PreOrderIterator.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/PreOrderIterator.cpp.o
.PHONY : Iterator/PreOrderIterator.cpp.o

Iterator/PreOrderIterator.i: Iterator/PreOrderIterator.cpp.i

.PHONY : Iterator/PreOrderIterator.i

# target to preprocess a source file
Iterator/PreOrderIterator.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/PreOrderIterator.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/PreOrderIterator.cpp.i
.PHONY : Iterator/PreOrderIterator.cpp.i

Iterator/PreOrderIterator.s: Iterator/PreOrderIterator.cpp.s

.PHONY : Iterator/PreOrderIterator.s

# target to generate assembly for a file
Iterator/PreOrderIterator.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/PreOrderIterator.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/PreOrderIterator.cpp.s
.PHONY : Iterator/PreOrderIterator.cpp.s

Iterator/UnaryIterator.o: Iterator/UnaryIterator.cpp.o

.PHONY : Iterator/UnaryIterator.o

# target to build an object file
Iterator/UnaryIterator.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/UnaryIterator.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/UnaryIterator.cpp.o
.PHONY : Iterator/UnaryIterator.cpp.o

Iterator/UnaryIterator.i: Iterator/UnaryIterator.cpp.i

.PHONY : Iterator/UnaryIterator.i

# target to preprocess a source file
Iterator/UnaryIterator.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/UnaryIterator.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/UnaryIterator.cpp.i
.PHONY : Iterator/UnaryIterator.cpp.i

Iterator/UnaryIterator.s: Iterator/UnaryIterator.cpp.s

.PHONY : Iterator/UnaryIterator.s

# target to generate assembly for a file
Iterator/UnaryIterator.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Iterator/UnaryIterator.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Iterator/UnaryIterator.cpp.s
.PHONY : Iterator/UnaryIterator.cpp.s

Op&Rand/Op.o: Op&Rand/Op.cpp.o

.PHONY : Op&Rand/Op.o

# target to build an object file
Op&Rand/Op.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make "CMakeFiles/test.dir/Op&Rand/Op.cpp.o"
	$(MAKE) -f CMakeFiles/lab.dir/build.make "CMakeFiles/lab.dir/Op&Rand/Op.cpp.o"
.PHONY : Op&Rand/Op.cpp.o

Op&Rand/Op.i: Op&Rand/Op.cpp.i

.PHONY : Op&Rand/Op.i

# target to preprocess a source file
Op&Rand/Op.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make "CMakeFiles/test.dir/Op&Rand/Op.cpp.i"
	$(MAKE) -f CMakeFiles/lab.dir/build.make "CMakeFiles/lab.dir/Op&Rand/Op.cpp.i"
.PHONY : Op&Rand/Op.cpp.i

Op&Rand/Op.s: Op&Rand/Op.cpp.s

.PHONY : Op&Rand/Op.s

# target to generate assembly for a file
Op&Rand/Op.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make "CMakeFiles/test.dir/Op&Rand/Op.cpp.s"
	$(MAKE) -f CMakeFiles/lab.dir/build.make "CMakeFiles/lab.dir/Op&Rand/Op.cpp.s"
.PHONY : Op&Rand/Op.cpp.s

Op&Rand/Rand.o: Op&Rand/Rand.cpp.o

.PHONY : Op&Rand/Rand.o

# target to build an object file
Op&Rand/Rand.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make "CMakeFiles/test.dir/Op&Rand/Rand.cpp.o"
	$(MAKE) -f CMakeFiles/lab.dir/build.make "CMakeFiles/lab.dir/Op&Rand/Rand.cpp.o"
.PHONY : Op&Rand/Rand.cpp.o

Op&Rand/Rand.i: Op&Rand/Rand.cpp.i

.PHONY : Op&Rand/Rand.i

# target to preprocess a source file
Op&Rand/Rand.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make "CMakeFiles/test.dir/Op&Rand/Rand.cpp.i"
	$(MAKE) -f CMakeFiles/lab.dir/build.make "CMakeFiles/lab.dir/Op&Rand/Rand.cpp.i"
.PHONY : Op&Rand/Rand.cpp.i

Op&Rand/Rand.s: Op&Rand/Rand.cpp.s

.PHONY : Op&Rand/Rand.s

# target to generate assembly for a file
Op&Rand/Rand.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make "CMakeFiles/test.dir/Op&Rand/Rand.cpp.s"
	$(MAKE) -f CMakeFiles/lab.dir/build.make "CMakeFiles/lab.dir/Op&Rand/Rand.cpp.s"
.PHONY : Op&Rand/Rand.cpp.s

Operators/Add.o: Operators/Add.cpp.o

.PHONY : Operators/Add.o

# target to build an object file
Operators/Add.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Add.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Add.cpp.o
.PHONY : Operators/Add.cpp.o

Operators/Add.i: Operators/Add.cpp.i

.PHONY : Operators/Add.i

# target to preprocess a source file
Operators/Add.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Add.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Add.cpp.i
.PHONY : Operators/Add.cpp.i

Operators/Add.s: Operators/Add.cpp.s

.PHONY : Operators/Add.s

# target to generate assembly for a file
Operators/Add.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Add.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Add.cpp.s
.PHONY : Operators/Add.cpp.s

Operators/Div.o: Operators/Div.cpp.o

.PHONY : Operators/Div.o

# target to build an object file
Operators/Div.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Div.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Div.cpp.o
.PHONY : Operators/Div.cpp.o

Operators/Div.i: Operators/Div.cpp.i

.PHONY : Operators/Div.i

# target to preprocess a source file
Operators/Div.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Div.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Div.cpp.i
.PHONY : Operators/Div.cpp.i

Operators/Div.s: Operators/Div.cpp.s

.PHONY : Operators/Div.s

# target to generate assembly for a file
Operators/Div.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Div.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Div.cpp.s
.PHONY : Operators/Div.cpp.s

Operators/Mult.o: Operators/Mult.cpp.o

.PHONY : Operators/Mult.o

# target to build an object file
Operators/Mult.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Mult.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Mult.cpp.o
.PHONY : Operators/Mult.cpp.o

Operators/Mult.i: Operators/Mult.cpp.i

.PHONY : Operators/Mult.i

# target to preprocess a source file
Operators/Mult.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Mult.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Mult.cpp.i
.PHONY : Operators/Mult.cpp.i

Operators/Mult.s: Operators/Mult.cpp.s

.PHONY : Operators/Mult.s

# target to generate assembly for a file
Operators/Mult.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Mult.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Mult.cpp.s
.PHONY : Operators/Mult.cpp.s

Operators/Pow.o: Operators/Pow.cpp.o

.PHONY : Operators/Pow.o

# target to build an object file
Operators/Pow.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Pow.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Pow.cpp.o
.PHONY : Operators/Pow.cpp.o

Operators/Pow.i: Operators/Pow.cpp.i

.PHONY : Operators/Pow.i

# target to preprocess a source file
Operators/Pow.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Pow.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Pow.cpp.i
.PHONY : Operators/Pow.cpp.i

Operators/Pow.s: Operators/Pow.cpp.s

.PHONY : Operators/Pow.s

# target to generate assembly for a file
Operators/Pow.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Pow.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Pow.cpp.s
.PHONY : Operators/Pow.cpp.s

Operators/Sub.o: Operators/Sub.cpp.o

.PHONY : Operators/Sub.o

# target to build an object file
Operators/Sub.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Sub.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Sub.cpp.o
.PHONY : Operators/Sub.cpp.o

Operators/Sub.i: Operators/Sub.cpp.i

.PHONY : Operators/Sub.i

# target to preprocess a source file
Operators/Sub.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Sub.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Sub.cpp.i
.PHONY : Operators/Sub.cpp.i

Operators/Sub.s: Operators/Sub.cpp.s

.PHONY : Operators/Sub.s

# target to generate assembly for a file
Operators/Sub.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Operators/Sub.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Operators/Sub.cpp.s
.PHONY : Operators/Sub.cpp.s

PrecisionAndSci/PrecisionOp.o: PrecisionAndSci/PrecisionOp.cpp.o

.PHONY : PrecisionAndSci/PrecisionOp.o

# target to build an object file
PrecisionAndSci/PrecisionOp.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/PrecisionOp.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/PrecisionOp.cpp.o
.PHONY : PrecisionAndSci/PrecisionOp.cpp.o

PrecisionAndSci/PrecisionOp.i: PrecisionAndSci/PrecisionOp.cpp.i

.PHONY : PrecisionAndSci/PrecisionOp.i

# target to preprocess a source file
PrecisionAndSci/PrecisionOp.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/PrecisionOp.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/PrecisionOp.cpp.i
.PHONY : PrecisionAndSci/PrecisionOp.cpp.i

PrecisionAndSci/PrecisionOp.s: PrecisionAndSci/PrecisionOp.cpp.s

.PHONY : PrecisionAndSci/PrecisionOp.s

# target to generate assembly for a file
PrecisionAndSci/PrecisionOp.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/PrecisionOp.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/PrecisionOp.cpp.s
.PHONY : PrecisionAndSci/PrecisionOp.cpp.s

PrecisionAndSci/PrecisionRand.o: PrecisionAndSci/PrecisionRand.cpp.o

.PHONY : PrecisionAndSci/PrecisionRand.o

# target to build an object file
PrecisionAndSci/PrecisionRand.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/PrecisionRand.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/PrecisionRand.cpp.o
.PHONY : PrecisionAndSci/PrecisionRand.cpp.o

PrecisionAndSci/PrecisionRand.i: PrecisionAndSci/PrecisionRand.cpp.i

.PHONY : PrecisionAndSci/PrecisionRand.i

# target to preprocess a source file
PrecisionAndSci/PrecisionRand.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/PrecisionRand.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/PrecisionRand.cpp.i
.PHONY : PrecisionAndSci/PrecisionRand.cpp.i

PrecisionAndSci/PrecisionRand.s: PrecisionAndSci/PrecisionRand.cpp.s

.PHONY : PrecisionAndSci/PrecisionRand.s

# target to generate assembly for a file
PrecisionAndSci/PrecisionRand.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/PrecisionRand.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/PrecisionRand.cpp.s
.PHONY : PrecisionAndSci/PrecisionRand.cpp.s

PrecisionAndSci/SciOp.o: PrecisionAndSci/SciOp.cpp.o

.PHONY : PrecisionAndSci/SciOp.o

# target to build an object file
PrecisionAndSci/SciOp.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/SciOp.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/SciOp.cpp.o
.PHONY : PrecisionAndSci/SciOp.cpp.o

PrecisionAndSci/SciOp.i: PrecisionAndSci/SciOp.cpp.i

.PHONY : PrecisionAndSci/SciOp.i

# target to preprocess a source file
PrecisionAndSci/SciOp.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/SciOp.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/SciOp.cpp.i
.PHONY : PrecisionAndSci/SciOp.cpp.i

PrecisionAndSci/SciOp.s: PrecisionAndSci/SciOp.cpp.s

.PHONY : PrecisionAndSci/SciOp.s

# target to generate assembly for a file
PrecisionAndSci/SciOp.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/SciOp.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/SciOp.cpp.s
.PHONY : PrecisionAndSci/SciOp.cpp.s

PrecisionAndSci/SciRand.o: PrecisionAndSci/SciRand.cpp.o

.PHONY : PrecisionAndSci/SciRand.o

# target to build an object file
PrecisionAndSci/SciRand.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/SciRand.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/SciRand.cpp.o
.PHONY : PrecisionAndSci/SciRand.cpp.o

PrecisionAndSci/SciRand.i: PrecisionAndSci/SciRand.cpp.i

.PHONY : PrecisionAndSci/SciRand.i

# target to preprocess a source file
PrecisionAndSci/SciRand.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/SciRand.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/SciRand.cpp.i
.PHONY : PrecisionAndSci/SciRand.cpp.i

PrecisionAndSci/SciRand.s: PrecisionAndSci/SciRand.cpp.s

.PHONY : PrecisionAndSci/SciRand.s

# target to generate assembly for a file
PrecisionAndSci/SciRand.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/PrecisionAndSci/SciRand.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/PrecisionAndSci/SciRand.cpp.s
.PHONY : PrecisionAndSci/SciRand.cpp.s

Sort/BubbleSort.o: Sort/BubbleSort.cpp.o

.PHONY : Sort/BubbleSort.o

# target to build an object file
Sort/BubbleSort.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sort/BubbleSort.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Sort/BubbleSort.cpp.o
.PHONY : Sort/BubbleSort.cpp.o

Sort/BubbleSort.i: Sort/BubbleSort.cpp.i

.PHONY : Sort/BubbleSort.i

# target to preprocess a source file
Sort/BubbleSort.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sort/BubbleSort.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Sort/BubbleSort.cpp.i
.PHONY : Sort/BubbleSort.cpp.i

Sort/BubbleSort.s: Sort/BubbleSort.cpp.s

.PHONY : Sort/BubbleSort.s

# target to generate assembly for a file
Sort/BubbleSort.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sort/BubbleSort.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Sort/BubbleSort.cpp.s
.PHONY : Sort/BubbleSort.cpp.s

Sort/SelectionSort.o: Sort/SelectionSort.cpp.o

.PHONY : Sort/SelectionSort.o

# target to build an object file
Sort/SelectionSort.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sort/SelectionSort.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Sort/SelectionSort.cpp.o
.PHONY : Sort/SelectionSort.cpp.o

Sort/SelectionSort.i: Sort/SelectionSort.cpp.i

.PHONY : Sort/SelectionSort.i

# target to preprocess a source file
Sort/SelectionSort.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sort/SelectionSort.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Sort/SelectionSort.cpp.i
.PHONY : Sort/SelectionSort.cpp.i

Sort/SelectionSort.s: Sort/SelectionSort.cpp.s

.PHONY : Sort/SelectionSort.s

# target to generate assembly for a file
Sort/SelectionSort.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sort/SelectionSort.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/Sort/SelectionSort.cpp.s
.PHONY : Sort/SelectionSort.cpp.s

decorators/Abs.o: decorators/Abs.cpp.o

.PHONY : decorators/Abs.o

# target to build an object file
decorators/Abs.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Abs.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Abs.cpp.o
.PHONY : decorators/Abs.cpp.o

decorators/Abs.i: decorators/Abs.cpp.i

.PHONY : decorators/Abs.i

# target to preprocess a source file
decorators/Abs.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Abs.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Abs.cpp.i
.PHONY : decorators/Abs.cpp.i

decorators/Abs.s: decorators/Abs.cpp.s

.PHONY : decorators/Abs.s

# target to generate assembly for a file
decorators/Abs.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Abs.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Abs.cpp.s
.PHONY : decorators/Abs.cpp.s

decorators/Ceil.o: decorators/Ceil.cpp.o

.PHONY : decorators/Ceil.o

# target to build an object file
decorators/Ceil.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Ceil.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Ceil.cpp.o
.PHONY : decorators/Ceil.cpp.o

decorators/Ceil.i: decorators/Ceil.cpp.i

.PHONY : decorators/Ceil.i

# target to preprocess a source file
decorators/Ceil.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Ceil.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Ceil.cpp.i
.PHONY : decorators/Ceil.cpp.i

decorators/Ceil.s: decorators/Ceil.cpp.s

.PHONY : decorators/Ceil.s

# target to generate assembly for a file
decorators/Ceil.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Ceil.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Ceil.cpp.s
.PHONY : decorators/Ceil.cpp.s

decorators/Floor.o: decorators/Floor.cpp.o

.PHONY : decorators/Floor.o

# target to build an object file
decorators/Floor.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Floor.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Floor.cpp.o
.PHONY : decorators/Floor.cpp.o

decorators/Floor.i: decorators/Floor.cpp.i

.PHONY : decorators/Floor.i

# target to preprocess a source file
decorators/Floor.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Floor.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Floor.cpp.i
.PHONY : decorators/Floor.cpp.i

decorators/Floor.s: decorators/Floor.cpp.s

.PHONY : decorators/Floor.s

# target to generate assembly for a file
decorators/Floor.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Floor.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Floor.cpp.s
.PHONY : decorators/Floor.cpp.s

decorators/Paren.o: decorators/Paren.cpp.o

.PHONY : decorators/Paren.o

# target to build an object file
decorators/Paren.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Paren.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Paren.cpp.o
.PHONY : decorators/Paren.cpp.o

decorators/Paren.i: decorators/Paren.cpp.i

.PHONY : decorators/Paren.i

# target to preprocess a source file
decorators/Paren.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Paren.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Paren.cpp.i
.PHONY : decorators/Paren.cpp.i

decorators/Paren.s: decorators/Paren.cpp.s

.PHONY : decorators/Paren.s

# target to generate assembly for a file
decorators/Paren.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Paren.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Paren.cpp.s
.PHONY : decorators/Paren.cpp.s

decorators/Trunc.o: decorators/Trunc.cpp.o

.PHONY : decorators/Trunc.o

# target to build an object file
decorators/Trunc.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Trunc.cpp.o
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Trunc.cpp.o
.PHONY : decorators/Trunc.cpp.o

decorators/Trunc.i: decorators/Trunc.cpp.i

.PHONY : decorators/Trunc.i

# target to preprocess a source file
decorators/Trunc.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Trunc.cpp.i
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Trunc.cpp.i
.PHONY : decorators/Trunc.cpp.i

decorators/Trunc.s: decorators/Trunc.cpp.s

.PHONY : decorators/Trunc.s

# target to generate assembly for a file
decorators/Trunc.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/decorators/Trunc.cpp.s
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/decorators/Trunc.cpp.s
.PHONY : decorators/Trunc.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/lab.dir/build.make CMakeFiles/lab.dir/main.cpp.s
.PHONY : main.cpp.s

unit_test.o: unit_test.cpp.o

.PHONY : unit_test.o

# target to build an object file
unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.o
.PHONY : unit_test.cpp.o

unit_test.i: unit_test.cpp.i

.PHONY : unit_test.i

# target to preprocess a source file
unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.i
.PHONY : unit_test.cpp.i

unit_test.s: unit_test.cpp.s

.PHONY : unit_test.s

# target to generate assembly for a file
unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.s
.PHONY : unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... lab"
	@echo "... install/strip"
	@echo "... install"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... AbstractFactorySubs/Precision.o"
	@echo "... AbstractFactorySubs/Precision.i"
	@echo "... AbstractFactorySubs/Precision.s"
	@echo "... AbstractFactorySubs/Sci.o"
	@echo "... AbstractFactorySubs/Sci.i"
	@echo "... AbstractFactorySubs/Sci.s"
	@echo "... AbstractFactorySubs/StdDouble.o"
	@echo "... AbstractFactorySubs/StdDouble.i"
	@echo "... AbstractFactorySubs/StdDouble.s"
	@echo "... Containers/ListContainer.o"
	@echo "... Containers/ListContainer.i"
	@echo "... Containers/ListContainer.s"
	@echo "... Containers/VectorCont.o"
	@echo "... Containers/VectorCont.i"
	@echo "... Containers/VectorCont.s"
	@echo "... Iterator/BinaryIterator.o"
	@echo "... Iterator/BinaryIterator.i"
	@echo "... Iterator/BinaryIterator.s"
	@echo "... Iterator/NullIterator.o"
	@echo "... Iterator/NullIterator.i"
	@echo "... Iterator/NullIterator.s"
	@echo "... Iterator/PreOrderIterator.o"
	@echo "... Iterator/PreOrderIterator.i"
	@echo "... Iterator/PreOrderIterator.s"
	@echo "... Iterator/UnaryIterator.o"
	@echo "... Iterator/UnaryIterator.i"
	@echo "... Iterator/UnaryIterator.s"
	@echo "... Op&Rand/Op.o"
	@echo "... Op&Rand/Op.i"
	@echo "... Op&Rand/Op.s"
	@echo "... Op&Rand/Rand.o"
	@echo "... Op&Rand/Rand.i"
	@echo "... Op&Rand/Rand.s"
	@echo "... Operators/Add.o"
	@echo "... Operators/Add.i"
	@echo "... Operators/Add.s"
	@echo "... Operators/Div.o"
	@echo "... Operators/Div.i"
	@echo "... Operators/Div.s"
	@echo "... Operators/Mult.o"
	@echo "... Operators/Mult.i"
	@echo "... Operators/Mult.s"
	@echo "... Operators/Pow.o"
	@echo "... Operators/Pow.i"
	@echo "... Operators/Pow.s"
	@echo "... Operators/Sub.o"
	@echo "... Operators/Sub.i"
	@echo "... Operators/Sub.s"
	@echo "... PrecisionAndSci/PrecisionOp.o"
	@echo "... PrecisionAndSci/PrecisionOp.i"
	@echo "... PrecisionAndSci/PrecisionOp.s"
	@echo "... PrecisionAndSci/PrecisionRand.o"
	@echo "... PrecisionAndSci/PrecisionRand.i"
	@echo "... PrecisionAndSci/PrecisionRand.s"
	@echo "... PrecisionAndSci/SciOp.o"
	@echo "... PrecisionAndSci/SciOp.i"
	@echo "... PrecisionAndSci/SciOp.s"
	@echo "... PrecisionAndSci/SciRand.o"
	@echo "... PrecisionAndSci/SciRand.i"
	@echo "... PrecisionAndSci/SciRand.s"
	@echo "... Sort/BubbleSort.o"
	@echo "... Sort/BubbleSort.i"
	@echo "... Sort/BubbleSort.s"
	@echo "... Sort/SelectionSort.o"
	@echo "... Sort/SelectionSort.i"
	@echo "... Sort/SelectionSort.s"
	@echo "... decorators/Abs.o"
	@echo "... decorators/Abs.i"
	@echo "... decorators/Abs.s"
	@echo "... decorators/Ceil.o"
	@echo "... decorators/Ceil.i"
	@echo "... decorators/Ceil.s"
	@echo "... decorators/Floor.o"
	@echo "... decorators/Floor.i"
	@echo "... decorators/Floor.s"
	@echo "... decorators/Paren.o"
	@echo "... decorators/Paren.i"
	@echo "... decorators/Paren.s"
	@echo "... decorators/Trunc.o"
	@echo "... decorators/Trunc.i"
	@echo "... decorators/Trunc.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... unit_test.o"
	@echo "... unit_test.i"
	@echo "... unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

